### ISSUE TITLE
Really slow with thousands of branches

### ISSUE THREAD

**Issue by arturadib** [rowanj/gitx#104]
I know, I know, it's bad and we should clean up after ourselves, but it'd be nice if Gitx didn't lock for 1/2 a minute before displaying the tree of a repo with thousands of branches.

The `.git/` dir itself is about 200M, and when I remote all of the remote branches and leave only a few local ones Gitx starts in a snap.

Many thanks for keeping this project up!

**Comment by rowanj** [comment]
Needs testing in 0.14.83+ which has changes from #158 (#157)

**Comment by arturadib** [comment]
wohoo works like a charm, thanks!

**Comment by rowanj** [comment]
Awesome! Praise to @micampe !

**Comment by rowanj** [comment]
@arturadib I'd love if you could test https://github.com/rowanj/gitx/releases/tag/builds/testing/1 - it changes nearly all of the history loading, and will be in the next build unless it has severe performance regressions.

**Comment by arturadib** [comment]
hey there, I downloaded the build and it seems to perform about the same as before for me.

**Comment by rowanj** [comment]
Excellent! That's pretty much what I wanted to hear.  Thanks @arturadib.
