### ISSUE TITLE
Add right click 'delete' for untracked changes

### ISSUE THREAD

**Issue by ghost** [rowanj/gitx#111]
A few GitX branches support deleting files directly from GitX.  It's useful for cleaning up after a merge, and extremely useful for removing files that reside inside a bundle (where deleting from finder requires even more clicks)

http://i.minus.com/iboEeYWORLTJly.png

**Comment by jaywilliams** [comment]
:+1:

**Comment by firedev** [comment]
Yes please, this was one of my favorite features in GitX(L)

**Comment by joehoyle** [comment]
+1

**Comment by firedev** [comment]
Great, thank you! When is the release?

**Comment by rowanj** [comment]
As soon as I fix the builder - which I may not get done tonight; it's 2:15 AM here, and I have work in the morning ^_^
