### ISSUE TITLE
Small feature: quit app on ⌘+W

### ISSUE THREAD

**Issue by niksy** [rowanj/gitx#118]
When opened from Terminal via `gitx` command, I (and I think possibly many others) review what’s on the branch, do something with it and then close the app. But closing it with ⌘+V just closes the window, not the app itself.

Is there a possibility to add option in preferences to fully close the app if the app is opened through Terminal?

There is a [SIMBL plugin](https://github.com/toy/GitXPatch) which will do that, but I would like to avoid any type of SIMBL interactivity.

**Comment by rowanj** [comment]
This is incongruent with the Apple interface; use ⌘+Q to quit the application, ⌘+W to close the active window only.

See: [Apple's OSX Human Interface Guidelines](https://developer.apple.com/library/mac/#documentation/userexperience/Conceptual/AppleHIGuidelines/Intro/Intro.html)' section on [Keyboard Shortcuts](https://developer.apple.com/library/mac/#documentation/userexperience/Conceptual/AppleHIGuidelines/KeyboardShortcuts/KeyboardShortcuts.html#//apple_ref/doc/uid/TP40002725-CHDIGFBH)
