### ISSUE TITLE
Terminal usage, gitx: Unable to open GitX.app

### ISSUE THREAD

**Issue by perifer** [rowanj/gitx#12]
When using gitx in the terminal you get the message "Unable to open GitX.app" in 0.11. It works in 0.9.

**Comment by rowanj** [comment]
Seems to be working okay for me on Snow Leopard, but not Lion.
- Are you running on Lion?
- Does the error message include something along the lines of `LSOpenFromURLSpec() returned -10827 for application file://path/to/GitX.app/`?

**Comment by rowanj** [comment]
(accidentally closed)

**Comment by rowanj** [comment]
As a workaround (and probably what I'll use as a fix, i.e. what will be installed by the "Enable Terminal Usage..." item), you can use:

```
open -a GitX .
```

**Comment by perifer** [comment]
Sorry for the late respone. Yes, the error was on Lion. It works on my Snow Leopard too. There is no more error printed to the terminal except "Unable to open GitX.app" – I haven't looked in any logs.

`open -a GitX .` works as a fix but I would miss some options, e.g. opening gitx with the commit view.

**Comment by rowanj** [comment]
No worries at all, and thanks for the report; and the extra details.  I'm definitely looking into this further.
