### ISSUE TITLE
Git 1.8.1: New file: error: Malformed value for push.default: simple error: Must be one of nothing, matching, tracking or current. fatal: bad config file line 21 in /Users/me/.gitconfig

### ISSUE THREAD

**Issue by firedev** [rowanj/gitx#120]
Plus detached "head" is set as the current branch:

![](http://d.pr/i/8DNv+)

`git version 1.8.1`

`.gitconfig`:

```
[push]
    default = simple
```

**Comment by jtwalters** [comment]
Did you specify the correct git executable under Preferences? If you have one installed in /usr/local/bin then you'll want to specify that directly.

**Comment by firedev** [comment]
Thanks! I assumed it should pick it up automatically.

**Comment by rowanj** [comment]
@jtwalters gets the support badge, :100: points
