### ISSUE TITLE
Add the ability to ignore files from Unstaged Changes

### ISSUE THREAD

**Issue by firedev** [rowanj/gitx#122]
This would be very useful.

**Comment by mikezter** [comment]
Hi firedev! Why not just add these files to your project's `.gitignore`?

**Comment by firedev** [comment]
That's like saying - Why do I even need GitX when I can do everything in terminal?

**Comment by rowanj** [comment]
I'm interested in this; but there are some tricky interface considerations.

.gitignore files 'cascade' into subdirectories; and there's also the potential of a user's `~/.gitignore_global` configuration, so the question of which level to insert it in is probably the most important. 

There's also the matter of what to actually add - should we prompt for a pattern, just add the filename, or the exact path?

On a side note, does a user necessarily want to .gitignore the files at all - or perhaps just hide (or collapse...?) unrecognised files in the stage view...

**Comment by firedev** [comment]
Normally if I have new files I want to:
1. Add them to project – Works already
2. Delete them – This is missing from gitx-dev, exists in gitx(L)
3. Ignore them – Example: `database.yml` copied from `*.dist`

We can ignore a file 3 ways: 
1. Project `/.gitignore`
2. Folder `./.gitignore`
3. Global `git config --global core.excludefiles`

Normally I would want to add it only to the project's root `/.gitignore`, and that's that. But I can easily imagine how global ignore can get useful. Local-folder `./.gitignore` can be skipped.

So my suggestion is. By default add a file to `/.gitignore`, option-click: add to global ignore file, and maybe add to local folder gitignore with, say, shift-click.

But, again, the part I worry about the most is per-project ignoring. Hope that explains it.

Regarding hiding files – this is a bad practice, you can check anything on versioning, they always say - don't leave orphan files.

**Comment by rowanj** [comment]
Is that not what you get when you right-click in the file list and select "Ignore File(s)"?

![Screen Shot 2013-01-17 at 3 09 53 PM](https://f.cloud.github.com/assets/47049/73728/c99b9c86-605b-11e2-9389-65c582e0ddc8.png)

edit: the "Move to Trash" option is new, and will show up in 0.14.61+ on Mountain Lion.

**Comment by firedev** [comment]
Er.. I guess, sorry. O_o

I was sure there was no ignore when I have created this ticket.

**Comment by rowanj** [comment]
Heh - I'd forgotten it at the time, too.  It's still a sweet idea, but fortunately the design questions were already answered :grinning:

**Comment by firedev** [comment]
Aha! I knew I am not imaginging things. I can't ignore the file that is already in the project!

http://d.pr/i/iqdZ

Why would I want this? Because (like in this case) I want to keep the original file in the project but don't want to have  it committed every time just because Codekit reshuffles it's data, or when I patch `install` script to use my custom paths.
