### ISSUE TITLE
"Move to Trash (#111)" does not remove the file from the list 

### ISSUE THREAD

**Issue by firedev** [rowanj/gitx#132]
So you can't tell if it was really moved to trash or not without refreshing the project.

**Comment by rowanj** [comment]
I figured it'd be picked up by auto-refresh, but I hadn't counted on that being disabled (or slow)

**Comment by rowanj** [comment]
Testing this I found that the preference for enabling the repo watcher seems to have disappeared - that'll be coming back in the next build; too.
