### ISSUE TITLE
Two windows for same repository via the command line helper

### ISSUE THREAD

**Issue by cpojer** [rowanj/gitx#135]
I'm using the "gitx" command line handler and I'm regularly closing gitx. When I use the command line helper twice in the same folder, the same window will be opened twice.

Steps to reproduce:
- Type gitx on the command line inside a folder with a git repository
- GitX opens
- Close GitX (via cmd+q)
- Type gitx again
- The same window will appear twice.

**Comment by rowanj** [comment]
I'd expect this to be resolved in .64 or .70 - which version is this against?

**Comment by cpojer** [comment]
Thanks for your response. You are right, for whatever reason I was on .61.

**Comment by appden** [comment]
Yes, this was resolved for me as of 0.64 :)
