### ISSUE TITLE
gitx command line can't find git working directory if not in project root

### ISSUE THREAD

**Issue by bitboxer** [rowanj/gitx#140]
On my system the gitx command line utility always returns this:

```
Could not find a git working directory.
```

I am in a git working directory and git has no problems using that. The gitx Gui also can open and work on that directory.

GitX Version 0.14.80 development (0.14.80)
Git is installed using homebrew and currently I use version 1.8.1.1

**Comment by jucor** [comment]
@bitboxer: do you observe this behaviour when your `pwd` is at the root of the repository, or only when you are in a sub-directory of your repo? I have the problem only when in a sub-dir.

**Comment by bitboxer** [comment]
You are correct. I didn't notice that it was working in the root of the repo.

**Comment by atuttle** [comment]
I too run into this issue frequently and it's very frustrating. This was introduced in one of the last few updates; it hasn't always been this way.

**Comment by rowanj** [comment]
Got a fix for this coming in the next build; I introduced the bug when I was continuing the refactoring and simplification of the directory searching.

I'd assumed that the Objective-Git `- (id)[GTRepository initWithURL:]` method used the libgit2 `git_repository_open_ext` variant that searched for the .git directory as a user would expect; but the defaults seem to specify no searching.

**Comment by jucor** [comment]
Awesome, thanks Rowan!

**Comment by bitboxer** [comment]
:dancer:
