### ISSUE TITLE
Tab Interface

### ISSUE THREAD

**Issue by bcomnes** [rowanj/gitx#163]
I end up having a number different gitx windows open at one time quite often.  What do people think about adding a tabbed interface to Gitx, where the tabs could help consolidate different gitx windows for different repositories into a single window?  Textmate 2's tab interface comes to mind when thinking about how this could be done.

**Comment by mengelbrecht** [comment]
:+1: I am dealing with a fair number of repositories on a daily basis. Therefore I always have at least 3 GitX windows open at the same time.
Tabs would definitely improve my workflow.
