### ISSUE TITLE
word-diff instead of line-diff

### ISSUE THREAD

**Issue by atuttle** [rowanj/gitx#168]
I know it would be a big undertaking, but I don't see it mentioned anywhere here so I thought it would be worth at least having the discussion. Would it be possible to enable (possibly via a setting?) word diffs instead of line-diffs?

```
git diff --color-words foo.txt
```

**Comment by sampumon** [comment]
And GitHub has this [nice hybrid mode](https://github.com/rowanj/gitx/commit/795876d9bb881c2c0a3bac13c35969c47ae0d1cb).

**Comment by atuttle** [comment]
Where I see this having a lot of immediate use is when a large block of code is indented. It's tedious and annoying to compare the lines by hand and make sure that the only change was indentation.

**Comment by rowanj** [comment]
It'd be tricky, largely due to the existing implementation.  Not impossible, though.

My current question is if this would supplement or duplicate #151 (ignore whitespace in diff viewer)

**Comment by sampumon** [comment]
Supplement. @atuttle's comment is about #151, and re-indented lines are already hidden by unticking "show whitespace differences".

Word-diff would hilight the changed words on a diff line, so it's faster & less cognitive burden to see what has actually changed.

**Comment by muhqu** [comment]
@sampumon, @atuttle  I have just added pull req #243 which adds a hybrid mode like you were referring to. Tell me what you think?

**Comment by sampumon** [comment]
Seems like exactly what I was hoping for! @rowanj, would this be feasible to pull in? ❤

**Comment by atuttle** [comment]
As I commented on #243, this looks great. After the to-do's are done, I have no doubt this will be a tremendous addition to GitX. :+1:

**Comment by rowanj** [comment]
@sampumon @muhqu's changes are looking pretty good; they'll likely be in the next testing build.

**Comment by mitio** [comment]
Looks like this issue can be closed since #243 has been merged and released.
