### ISSUE TITLE
gitx does not show detached head in the tree

### ISSUE THREAD

**Issue by magicseth** [rowanj/gitx#189]
When committing on a detached head (ahead of any tag or branch) it does not show up in the tree.

clicking on "detached head" does not highlight any commit, because it is not visible.

**Comment by rowanj** [comment]
I think GitX only loads commits that are linked from a ref; so if you're ahead of any ref I understand the issue.

If HEAD is in the linked section of the tree, however, you should see at least that the commit's "dot" is orange.

Fix will be to load add HEAD to the loaded refs.

**Comment by magicseth** [comment]
Got it. This is a regression from the last sparkle version. I frequently have a head not on any of the linked tree. Your fix sounds good and I might get to it on Monday. 
- seth

**Comment by millerdev** [comment]
This bug is really annoying. Any chances that this might be fixed and a new version released sometime soon?

**Comment by magicseth** [comment]
I don't have time to work on it. My work around had been to drop to a
command line and add a tag. Reload gitx and then delete the tag when I'm
done.

**Comment by rowanj** [comment]
Yep, new version coming soon.
