### ISSUE TITLE
Re-blame Browsing (some work exists?)

### ISSUE THREAD

**Issue by ches** [rowanj/gitx#20]
Thanks for all the work that's gone into this fork, it's great to see a focus on maintainability that keeps the UI clean (and it's fast!). GitX has been pretty much feature-complete for my needs personally since @brotherbard's fork really, but there's one thing I would really love to see: the click-able SHAs in blame view that @kamal [contributed here](https://github.com/brotherbard/gitx/pull/90). Seems like a small change but I don't know how much has diverged... Is this a feature you guys are interested in?

**Comment by rowanj** [comment]
Nice find, @ches  -  expect a new build soon.

**Comment by ches** [comment]
And then a light shown down from above, Sparkle updated, and it was good.

Thanks! :smile:

**Comment by rowanj** [comment]
All too easy!  It does make the Blame view a whole lot more useful, eh?  I'd always kind of ignored it myself.

**Comment by ches** [comment]
I know you're not looking to add a lot of new features, but now I find myself wishing that I could do `gitx --blame <file>` with the command-line tool... :wink:

Maybe I'll see if I can dust off some Cocoa chops this weekend to make sense of it.
