### ISSUE TITLE
command line broke after last release of gitx

### ISSUE THREAD

**Issue by aschiopu** [rowanj/gitx#210]
Was working fine until the lastest release (today)
Now when i type gitx I get the following message.

Alexeis-MacBook-Air:plangrid-admin alexei$ gitx
dyld: Library not loaded: @rpath/ObjectiveGit.framework/ObjectiveGit
  Referenced from: /usr/local/bin/gitx
  Reason: image not found
Trace/BPT trap: 5

**Comment by rowanj** [comment]
Confirmed this problem, I should be able to push a fix as soon as I get home.

**Comment by rowanj** [comment]
Relates: #207

**Comment by khoan** [comment]
same error on OS X Mountain Lion 10.8.4 too

**Comment by kemenaran** [comment]
Workaround until the fix get merged:

```
alias gitx="open -a /Applications/GitX.app ."
```

**Comment by lossius** [comment]
Would you be able to provide an updated installer for Gitx with this fix? Thanks!

**Comment by lossius** [comment]
I see that you already did. Thanks, that was a swift fix, and much appreciated!

**Comment by j15e** [comment]
Thanks, got this error too! Fixed now!

**Comment by rowanj** [comment]
Closing (fixed)
