### ISSUE TITLE
Commandline tool broken

### ISSUE THREAD

**Issue by tmeasday** [rowanj/gitx#211]
Hi, first off, thanks for continuing dev on gitx, it's great, and the improvements bring a smile to my face.

Just upgraded to 0.14.92 dev and it broke my `gitx` command line executable:

``` bash
$ gitx
dyld: Library not loaded: @rpath/ObjectiveGit.framework/ObjectiveGit
  Referenced from: /usr/local/bin/gitx
  Reason: image not found
Trace/BPT trap: 5
```

I tried "Enable Terminal Usage" again, with no difference.

**Comment by rowanj** [comment]
Yep, this is broken in the latest build; sorry.  I should be able to push out the fix as soon as I get home.

Closing because it duplicates #210

**Comment by tmeasday** [comment]
Sorry for the dupe! For some reason when I hit the issues tab, the featured tag was selected. How bizzarre.

**Comment by rowanj** [comment]
Don't worry about it at all, I'd much rather have duplicates to close than bugs I don't know about ^_^
