### ISSUE TITLE
Branches not connecting properly in the tree in testing-2

### ISSUE THREAD

**Issue by rjmunro** [rowanj/gitx#247]
The below screenshot is using the https://github.com/rowanj/gitx/releases/tag/builds/testing/2 version.

As you can see there are 5 branches whose history streches down before the initial commit of the project, below where it it possible to scroll.

A hunch is that it might be related to me using a lot of cherry picking and `git rebase -i` to change the order of commits, so sometimes a commit is older than it's parent. This may be confusing the new history code.

![screen shot 2013-08-22 at 16 29 28](https://f.cloud.github.com/assets/108641/1009859/b4ccea0a-0b3f-11e3-93f0-e0acd94326a6.png)

**Comment by rowanj** [comment]
That's an interesting effect, I guess it hasn't read a valid date for those connected commits when it loaded them in.

Can you follow the "parent: " link of the branches in the commit details to get the missing commits?

**Comment by rjmunro** [comment]
Yes, at least sometimes, when I click a parent link, it takes me to the parent commit, (which appears above the current commit because it is newer).

I've done a bit of experimentation, and I can't recreate the problem easily on an empty-ish test repository by just cherry picking - the issue must be a bit involved.

**Comment by rowanj** [comment]
Ah, that could be the problem; if the parent commit is above the child in the list - I don't think the grapher will handle that well at all.

**Comment by rjmunro** [comment]
I haven't seen this in any released versions that have come out after the test version this was testing, so I am presuming it is fixed and closing.
