### ISSUE TITLE
Once columns are sorted, commit graph is unretrievable

### ISSUE THREAD

**Issue by ljharb** [rowanj/gitx#251]
When I open a repo, I see the nice commit dots and graph lines on the left. However, once I click a column heading (to sort by that heading), they disappear (which makes sense). However, there's no way to restore the original sorting without closing and reopening the repo.

**Comment by sugarmo** [comment]
You can just select any other branch (inclues remote branch) and then go back. But I do agree that there should be a button to undo sort.

**Comment by ljharb** [comment]
Ah, thanks for that! A button would be great.

(On another note, I'd love to be able to select _no_ branches, so the list always scrolls to the top when i refresh)

**Comment by rowanj** [comment]
I've actually been considering disabling the sort-by-columns feature; it seems to me to only be useful because the search tool sucks - is that the case?  If not, what are you using the sort-by for?

**Comment by rowanj** [comment]
@ljharb Agreed, the auto-scrolling is indeed buggy at best; ideally we should be able to insert commits without having to scroll at all in most cases.

**Comment by zamber** [comment]
You actually can restore the commit graph view by un-clicking a column with the blue bar (indicating sorting).

**Comment by ljharb** [comment]
@Zamber whoa, ok - that's VERY unexpected behavior for a column header. usually they toggle between descending and ascending, but in gitx they have a third option which is "deselected". That's very helpful to know, but I'd still rather see the column headers behave like every other app and OS ever rather than uniquely :-)

**Comment by Uncommon** [comment]
I actually found the three-state header to be fairly intuitive.

**Comment by zamber** [comment]
@ljharb, I'm not sure if this behaviour is mentioned in the [design guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/AppleHIGuidelines/Intro/Intro.html#//apple_ref/doc/uid/TP30000894-TP6). Did a quick skim and found nothing of interest.

Keep in mind that it's pre-fork functionality so it could be outdated.

**Comment by ljharb** [comment]
Obviously some will find it useful and some will find it confusing, and if it was mentioned in the design guidelines that'd have some weight. I'm just saying I've never seen that before in column headers that I can ever recall, on Macs or Windows, which suggests that it deviates from an unspoken convention. At the very least, I'd love to see an explicit header for the commit graph.

**Comment by zamber** [comment]
3 way sort is usually not needed or easily resolved with filtering. This is a special use case as the order is not dictated by commit data but by the tree rendering.

A header for the commit graph would require a whole separate column dedicated for it. This would make aligning commit messages tricky.

Given that it's fairly unusual behaviour of the columns a button for restoring would make some sense. IMHO an additional button would be ok for GitX (L), @rowanj keeps it simple.

**Comment by rowanj** [comment]
I actually didn't find the third column state until mentioned here :sheep:

**Comment by rowanj** [comment]
Anyway, closing this in favour of #252  - I will keep it simple, perhaps just some other decal to draw attention to the third state.
