### ISSUE TITLE
10.9 DP7: Crash on Cancelling Making New Repo

### ISSUE THREAD

**Issue by emiscience** [rowanj/gitx#255]
Issue:

When you first fire GitX up, click on File -> New then click on cancel, it crashes out.

Steps to reproduce:

1) Download Clean copy of GitX
2) Run the .app
3) Click on File Menu
4) Click on New
4) Press Cancel

Errors Received:

Process:         GitX [29023]
Path:            /Applications/GitX.app/Contents/MacOS/GitX
Identifier:      net.phere.GitX
Version:         0.14.95 dev (0.14.95)
Code Type:       X86-64 (Native)
Parent Process:  launchd [145]
Responsible:     GitX [29023]
User ID:         501

Date/Time:       2013-09-13 16:51:27.989 +0100
OS Version:      Mac OS X 10.9 (13A569)
Report Version:  11
Anonymous UUID:  _removed_

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000018

VM Regions Near 0x18:
--> 
    __TEXT                 000000010438f000-00000001043f4000 [  404K] r-x/rwx SM=COW  /Applications/GitX.app/Contents/MacOS/GitX

Other Notes:

Just to add, despite this being DP build of OSX, I'll take a look into what's causing this over the coming weekend.
- Adrian S

**Comment by justrjlewis** [comment]
+1

**Comment by justrjlewis** [comment]
Looks like there's pull request pending: https://github.com/ksuther/gitx/commit/7db8e7cd8e67f2af6afe08f4c70cc546a7af16c9
