### ISSUE TITLE
Command line launcher crashes on 10.9 DP 7

### ISSUE THREAD

**Issue by ulope** [rowanj/gitx#256]
The cli launcher crashes under OS X 10.9 DP 7 with the following message:
[1]    1445 trace trap  gitx

Here is the output of `sudo dtruss gitx`: http://cl.ulo.pe/text/0x3R0J2T1d2K

**Comment by ulope** [comment]
Just a short update: The same problem still exists on 10.9 DP 8

Until this is sorted out I'm using this workaround:

``` shell
# Put this in your shell config:
alias gitx='osascript -e "tell application \"GitX\" to open \"$(pwd)\"" -e "tell application \"GitX\" to activate" '
```

**Comment by appden** [comment]
Is this is an issue on GM? I'm not experiencing this anymore.

**Comment by ulope** [comment]
Yes, the problem seems to have vanished in the GM release of Mavericks
