### ISSUE TITLE
Have renamed / moved files show up as 'renamed', not as deleted / added in 'Staged changes

### ISSUE THREAD

**Issue by wrtsprt** [rowanj/gitx#258]
Renaming / moving a file (`git mv`) will show it as renamed in e.g. `git stash`. In the gitx Staged changes table, they will show up as deleted and added. 

![screen shot 2013-10-18 at 14 21 13](https://f.cloud.github.com/assets/36982/1360122/ed0249ce-37ef-11e3-8a12-0c852a348148.png)
![screen shot 2013-10-18 at 14 21 31](https://f.cloud.github.com/assets/36982/1360127/efb32422-37ef-11e3-8dbb-675f5c2bab89.png)

**Comment by rowanj** [comment]
This is showing precisely what the `git` operation does - it removes the old file and adds the new one.

Rename detection is done at the time of showing the diff, as `git status` is showing in the screenshot.  This task would be to add such rename detection and an appropriate status to GitX; which is further complicated by files that may be modified as well as renamed - which I don't think could be easily represented with our current UI without dropping other useful behaviours like discarding the deletion.
