### ISSUE TITLE
OSX 10.6.8 _objc_release not found 

### ISSUE THREAD

**Issue by SwissalpS** [rowanj/gitx#265]
Process:         GitX [1690]
Path:            /Applications/GitX.app/Contents/MacOS/GitX
Identifier:      net.phere.GitX
Version:         0.14.95 dev (0.14.95)
Code Type:       X86-64 (Native)
Parent Process:  launchd [459]

Date/Time:       2013-11-20 16:45:29.121 +0100
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Symbol not found: _objc_release
  Referenced from: /Applications/GitX.app/Contents/MacOS/../Frameworks/ObjectiveGit.framework/ObjectiveGit
  Expected in: /usr/lib/libobjc.A.dylib
 in /Applications/GitX.app/Contents/MacOS/../Frameworks/ObjectiveGit.framework/ObjectiveGit

**Comment by EdyJ** [comment]
Same exact problem here, with same exact details (only the processId is different).

**Comment by xpe** [comment]
@SwissalpS @EdyJ Is this a run-time or compile-time error? Can you provide more details?

Let's help out the developers and provide as much information as possible. See https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines for some nice suggestions.

**Comment by EdyJ** [comment]
Which other details could be useful? Launching GitX crashed with the above crash report.
I switched to "GitX (L)" ([Laullon fork](http://gitx.laullon.com)), which works perfectly.

**Comment by rowanj** [comment]
It's a run-time error due to Snow Leopard not supporting Objective-C ARC.

10.6 is not supported after the last release to use Garbage Collection - 0.14.81; grab the last Snow Leopard binary from https://github.com/rowanj/gitx/releases/tag/builds%2F0.14%2F81
