### ISSUE TITLE
Development Instructions Are Incomplete

### ISSUE THREAD

**Issue by danyowdee** [rowanj/gitx#267]
As it stands, attempting to build the master branch after following the steps described in the project’s read me document fails in the Objective-Git framework, sporting the following error message:

```
$(PROJECT_DIR)/objective-git/External/libgit2/include/git2/transport.h:15:10: 'libssh2.h' file not found
```

The reason appears to be, that…
1. GitX’s indirect dependency on Homebrew isn’t listed—this would also simplify getting CMake on your machine.
2. The dependency on running Objective-Git’s `bootstrap` script (which in turn depends on xctool) isn’t listed.

**Comment by rowanj** [comment]
Good point, the openssh dependency was added recently as libgit2/libgit2 adds their ssh transport.
