### ISSUE TITLE
Programmatically add Command Line Tool

### ISSUE THREAD

**Issue by hjhart** [rowanj/gitx#269]
Is there a way to programmatically (e.g. from the command line) add the /usr/local/bin/gitx command line tool without having to open the application?

I'm trying to automate my company's workstations installation from soup-to-nuts and this is one of the few things I repeatedly have to do when we start development on a freshly automated machine.

Any help is appreciated!

**Comment by tiennou** [comment]
As far as I can see, the `gitx` CLI tool ca be found inside the bundle's Resources folder. A "programmatic" way would be to `ln -s` that into `/usr/local/bin` (that's what the app does IIRC, to allow updates of the main app to give new powers to `gitx`).

**Comment by hjhart** [comment]
Oh, der. 

Thanks @tiennou – this will turn out to be an obvious fix then. I only `cat`ed the file, I didn't check to see if it was a symlink!

Thanks,
James
