### ISSUE TITLE
feature request: add GitX (L) style submodule section to sidebar

### ISSUE THREAD

**Issue by kjg** [rowanj/gitx#27]

**Comment by rowanj** [comment]
I do want to improve the submodules significantly, especially when tracking multiple upstreams.  This is used by my own work on this project itself to handle using patches that aren't merged into upstream [libgit2](/libgit2/libgit2) or [objective-git](/libgit2/objective-git).

I must admit that I'm not especially familiar with current GitX (L), but it sounds like I'll be able to identify the feature you refer to easily enough.

Related issue #4 deals with refreshing the index w/ submodule changes.

**Comment by kjg** [comment]
Here is the submodule sidebar section in GitX (L).

In my opinion the "Other" section can probably be removed as well because what ever falls into other?

![sidebar](http://i.imgur.com/JhMSk.png)

**Comment by rowanj** [comment]
Thanks for the pic, that seems pretty clear.  I assume that objective-git item expands to show the libgit2 sub-submodule.

On a related note, I think submodules need to be better integrated in the staging/commit workflow as well.

**Comment by magicseth** [comment]
I have a partial implementation at https://github.com/magicseth/gitx/tree/master
It doesn't have icons, nor does it specify which commit (or tag) the submodule is at
