### ISSUE TITLE
UTF-16le text encoding considered a binary file by gitx

### ISSUE THREAD

**Issue by klaw23** [rowanj/gitx#270]

**Comment by sjmadsen** [comment]
I don't think this is a GitX problem. Git itself doesn't know how to deal with UTF-16LE encoded text files. Try `git diff` from Terminal and you'll see the same message.

A possible fix, at least for `.strings` files, is to add the following line to the `.gitattributes` file at the top of your project:

```
*.strings set diff
```

`git diff` output is a complete mess, but the diff looks good in GitX, at least for characters that also exist in ISO-8859-1.

**Comment by klaw23** [comment]
That works great, thanks!
