### ISSUE TITLE
Can't handle commit-msg hook

### ISSUE THREAD

**Issue by savetheclocktower** [rowanj/gitx#279]
I'm working in a repo that has both a `pre-commit` hook and a `commit-msg` hook. Commits from GitX always fail. The "Commit hook failed" window reports that the `commit-msg` hook failed, but it shows the output from the `pre-commit` hook, and only that hook. I can verify that the same commit passes from the command line.

I don't know if this is a bug specific to the `commit-msg` hook or whether GitX gets confused with multiple hooks. I can try to reproduce this in an empty repo if necessary.

**Comment by savetheclocktower** [comment]
Closing this because I did try it with an empty repo and everything works as expected. I still can't explain this, so I'll do some more troubleshooting.

**Comment by rowanj** [comment]
Do keep me posted.
