### ISSUE TITLE
word-diff

### ISSUE THREAD

**Issue by alexandreroberts** [rowanj/gitx#297]
I use git to track versions of my dissertation and other prose documents in the humanities, so it would be great for me if I could use the `--word-diff` option of `git diff` (plus line-wrapping) in the GitX GUI's `diff` display, with an option to set it as the default.

**Comment by rowanj** [comment]
Merged in 0.15

**Comment by alexandreroberts** [comment]
Does this mean that it is now possible to use `--word-diff` in GitX? I downloaded the new version (0.15.1899), but I haven't been able to figure out how to change the `git diff` option used by GitX.
