### ISSUE TITLE
Directed acyclic Graph wrong?

### ISSUE THREAD

**Issue by tkreuder** [rowanj/gitx#303]
When i open the gitx repository in gitx, the graph representation seems to be wrong.
There are three "master" branches / lanes instead of one and they do not end with a commit.

![gitx_graph_error](https://cloud.githubusercontent.com/assets/385110/2664578/c8e995ae-c07c-11e3-9695-51600a8847ab.jpg)

in comparison the git graph looks like the following:

![git_graph](https://cloud.githubusercontent.com/assets/385110/2664606/35b01118-c07d-11e3-9495-f6487c6fe210.jpg)

**Comment by rowanj** [comment]
Are you seeing this with the current (0.15.*) version?

**Comment by DeMayo** [comment]
I'm seeing this with version (0.15.1869).
It started when I swapped two commits with git rebase -i on the command line and created a new branch from the now earlier commit.

**Comment by DeMayo** [comment]
(cont) The earliest commit in the dangling branch has a correct parent entry (can even jump to that when clicking on it in gitx) but that parent entry is sorted above it in the default view.

**Comment by rowanj** [comment]
0.15.x moved to a new history enumeration strategy; and sorting by commit time gave a much better overview of parallel activity on concurrent branches, but introduced this bug in some repos with out-of-order commits (i.e. due to rebase).

Should be fixed by changes tagged in #330 in the next build.
