### ISSUE TITLE
Submodule update

### ISSUE THREAD

**Issue by basecode** [rowanj/gitx#305]
I run into problems building (a fresh) GitX. Looks like it's due to an linking issue within `objective-git` in combination with libssh2. See https://github.com/libgit2/objective-git/issues/352. I wonder if it could be fixed by pointing to a newer version of `objective-git`? Currently  
.gitmodule points to a 4 month old `objective-git` version.

![screen shot 2014-04-29 at 8 59 31 pm](https://cloud.githubusercontent.com/assets/143527/2833442/7bec469e-cfd0-11e3-87b1-d2ed4cf7146c.png)

**Comment by rowanj** [comment]
Yep, fixed upstream
