### ISSUE TITLE
'-fcatch-undefined-behavior' is deprecated while build ObjectiveGit

### ISSUE THREAD

**Issue by athurg** [rowanj/gitx#308]
the error message is 

```
clang: error: argument '-fcatch-undefined-behavior' is deprecated, use '-fsanitize=undefined-trap -fsanitize-undefined-trap-on-error' instead
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

to fix this, change ObjectiveGit's **OTHER_CFLAGS**, replace `"$(inherited)"` with `"-ftrapv"`.

**Comment by rowanj** [comment]
Should be fixed on `master`.

FYI, you shouldn't get rid of the "$(inherited)" in a target build setting unless you really want the project and xcconfig level settings to not be applied.
