### ISSUE TITLE
Showing large commit is broken in release 0.15.1869

### ISSUE THREAD

**Issue by tkareine** [rowanj/gitx#310]
When displaying a large commit, GitX shows a label to click for actually displaying the commit diff ("This is a large commit. Click here or press 'v' to view."). But when clicking the label, I see the diff appear and disappear briefly in a flash, and then the label reappears.

To reproduce:
1. Clone a repository, such as Rails, `git clone git@github.com:rails/rails.git`
2. Open GitX in the repository
3. Find a large commit, such as [b95d6e8](https://github.com/rails/rails/commit/b95d6e8)
4. Click the label "This is a large commit. Click here or press 'v' to view." in the diff panel

What should happen: GitX shows the commit diff.

What actually happens: diff appears and disappears quickly, the label reappears.

**Comment by tkareine** [comment]
This message gets printed in `/var/log/system.log` when I click the label:

```
May 12 14:00:15 xxx GitX[30845]: Error from webkit: {
            MessageLevel = ErrorMessageLevel;
            MessageSource = JSMessageSource;
            columnNumber = 22;
            lineNumber = 470;
            message = "TypeError: 'undefined' is not an object (evaluating 'ns[ n[i] ].rows.push')";
            sourceURL = "file:///Applications/GitX.app/Contents/Resources/html/lib/diffHighlighter.js";
        }
```

**Comment by sugarmo** [comment]
How about reinstall **GitX**?

**Comment by dgreensp** [comment]
I get the same error message and line number, and it's not a big commit.

There's one file which, when I select it under "Unstaged changes," simply doesn't show a diff.  The window doesn't update.

**Comment by sugarmo** [comment]
Try to stage all files and then unstage all files.

GitX use *git-update-index *inside to implement staging, I don't know much
about that, but I know there is an issue about staging particular lines in
a single file.

**Comment by dgreensp** [comment]
Found the problem.  Any diff with the word "constructor" in it (or any of a number of other words) will break the diff highlighter completely.

I'll try to put together a PR.

**Comment by dgreensp** [comment]
See #320

**Comment by millerdev** [comment]
I have this issue too. Makes it impossible to view the content of large commits. Please fix.

**Comment by rowanj** [comment]
Most likely due to the word-highlighting changes.

Any thoughts, @muhqu?

**Comment by muhqu** [comment]
@rowanj exactly the right fix by @dgreensp :+1:
