### ISSUE TITLE
GitX (0.15.1869) sometimes shows HEAD for origins

### ISSUE THREAD

**Issue by tfeb** [rowanj/gitx#312]
I generally work in a repo which is cloned from a bare master repo on the same machine.  So my work pattern is something like:

```
$ git init --bare myproj.git
$ cd ...; git clone .../myproj.git; cd myproj
$ vi .gitignore; git add .gitignore; git commit -m ...; git push origin master
... git commits ...
$ git push
...
```

Previously, GitX would show `master` and `origin/master` (and other branches of course if they exist). After 0.15.1869 it also shows, for some repos (not all, and I don't understand which ones) `origin/HEAD`.  This isn't really a bug, but I don't think it's useful either.  There is an example screenshot below (the weird commit names are intentional: the commits are done by a script every hour).

I am using running 10.9.2 using the git that comes with OSX (or with Xcode perhaps). I'm not building GitX from source, just using the binary and letting it update itself when it wants.

Feel free to close this if it's either intentional or not worth fixing!

![Example screenshot](https://cloud.githubusercontent.com/assets/2299342/2944548/f93c1440-d9d4-11e3-8e29-1c2e978a81b6.png)

**Comment by rowanj** [comment]
Special thanks for the great report, including pics, description, and relevant version numbers :thumbsup:

**Comment by tfeb** [comment]
I've just tried 0.15.1899 which fixes this: thanks.  It said an odd thing about "locked with a password" when updating but I just hit cancel and it did it anyway...

**Comment by rowanj** [comment]
That is a very odd thing to encounter, perhaps it's an interaction with auto-updates replacing the bundle and 10.9.2.  Do you have GitX installed in `/Applications`, or somewhere else?

**Comment by tfeb** [comment]
It's in `/Local/Applications` which is where I keep local things: it's a directory I can write to as a non-admin user basically.  My guess is that it was some transient 10.9.\* oddness, since it didn't happen for 0.15.1869.  I'll let you know if it happens again (assuming you want to: it's not exactly a blocking problem...)
