### ISSUE TITLE
various, 0.15.1869 seems not ready for production

### ISSUE THREAD

**Issue by claybridges** [rowanj/gitx#313]
1. It asked me for a password on install. Ooookaaay. I skipped it and it worked fine, but still.
2. GitX shows a topic branch which exists on master as independent of master. `flow` goes down 100+ commits in the display, but that's simply not true.

![screen shot 2014-05-12 at 11 12 42 am](https://cloud.githubusercontent.com/assets/96004/2946088/41830840-d9e8-11e3-9bdf-f065ee0541b3.png)

**Comment by sdegutis** [comment]
Ditto.

**Comment by rowanj** [comment]
Commit date sorting issue; fixed by #330
