### ISSUE TITLE
Word diff highlighting breaks for swapped phrases

### ISSUE THREAD

**Issue by mitio** [rowanj/gitx#321]
Here is an example rendering of the word diff which highlights the wrong parts of the sentence:

![wrong word diff rendering](https://cloud.githubusercontent.com/assets/129307/2956410/d0399a80-da8e-11e3-8b23-5dde993d3afc.png)

GitX version: 0.15.1869 dev (0.15.1869)

@muhqu created [a pen](http://codepen.io/anon/pen/BkHrD) demonstrating the issue.

Related to #243

**Comment by muhqu** [comment]
@mitio I found a way and updated the pen: http://codepen.io/muhqu/pen/FcmjB

**Comment by mitio** [comment]
Yes, this looks better. It seems though that it detects the spaces as separate changes as well.

Here's how Git returns the word diff: `Foo[-Bar-] Baz {+Bar+} Barf` Maybe we should try to achieve something similar?

**Comment by rowanj** [comment]
Merged @muhqu's fix

**Comment by mitio** [comment]
Thanks!
