### ISSUE TITLE
Ability to disable graphical shadows introduced in 0.15.1869

### ISSUE THREAD

**Issue by martindines** [rowanj/gitx#322]
0.15.1869 brought with it various graphical updates.

In my opinion the colour palette contrast has decreased making it harder to identify branch trees - with the added shadow aiding this by removing needed white space.

It would be great to have the option to turn off this updated (3D) style in favour for the _classic_ gitx style as per pre0.15.1869

![](http://s.gpmd.net/4b38e6.png)

![](http://s.gpmd.net/a4e49b.png)

**Comment by beporter** [comment]
:-1: to more preferences. If anything, I say go with the prevailing opinion in #315 and just revert.

**Comment by rowanj** [comment]
The reduced whitespace is reduced, to compact the effect of the tree lines taking up too much space on active projects with many branches.

Reducing the shadow and increasing the colour contrast is a more likely option; I'm not introducing visual style preferences or configuration.
