### ISSUE TITLE
history truncated by tags

### ISSUE THREAD

**Issue by danielnorberg** [rowanj/gitx#324]
For some git repositories, the commit history view seems to become truncated by the presence of tags.

The history just "starts" in mid-air with the commit after a tagged commit and with the parent link referring to a tagged parent commit id that doesn't show up. Removing the offending tag makes gitx show more of the history, up to the next tag that it doesn't like. Removing all tags makes gitx show the entire history, but fetching all tags again truncates the history view.

There does not seem to be any related error messages in the console log.

This problem can be reproduced with the jersey git repo: https://github.com/jersey/jersey. The history view of the master branch simply ends at d8c6a5c.

Version 0.15.1869 dev (0.15.1869)

**Comment by rowanj** [comment]
Thanks for the test repo; should be fixed by changes under #330 in the next release.

**Comment by danielnorberg** [comment]
sweet!
