### ISSUE TITLE
Build problem with the current source state

### ISSUE THREAD

**Issue by ghost** [rowanj/gitx#327]
I fail to update the submodule, bad commit reference, a commit not pushed in objective-Git ?

fatal: reference is not a tree: 281c0c8621fbd50493a6993ff7d4b959e8273fa3
Unable to checkout '281c0c8621fbd50493a6993ff7d4b959e8273fa3' in submodule path 'objective-git'

b8f9ff5 Latest objective-git
diff --git a/objective-git b/objective-git
index 569c622..281c0c8 160000
--- a/objective-git
+++ b/objective-git
@@ -1 +1 @@
-Subproject commit 569c62299c7186ebb66ad9e8761bacae8090e842
+Subproject commit 281c0c8621fbd50493a6993ff7d4b959e8273fa3

**Comment by rowanj** [comment]
That's exactly the problem, fixing it now; sorry.

**Comment by ghost** [comment]
Ok, thanx... Don't worry... This tool is helping me a lot to use Git on my project

Wiling to contribute, if you need some help...

**Comment by rowanj** [comment]
Thanks for the offer!  The push is done now, so you should be good to go.

**Comment by ghost** [comment]
It did work, checked tags and so, build different tags and it works, but I don't understand why the About panel has not the right version ? Your delivery process do something special ?

**Comment by rowanj** [comment]
Yep, the scripts that prepare the release builds set the version number.

Development builds always have a 0.12 build number; mostly so that they're always distinct from published builds when people are reporting bugs - so that I know to ask what actual code they were running.

**Comment by ghost** [comment]
Good point ;)
