### ISSUE TITLE
Dashed lines are distractingly dashed...

### ISSUE THREAD

**Issue by kubat** [rowanj/gitx#329]
The dashed lines are, well, too dashed. 
They create a visual break in the flow, and seem to be incorrect. 

See below: 
![screen shot 2014-05-15 at 9 50 18 pm](https://cloud.githubusercontent.com/assets/474757/2992827/8690d186-dc9c-11e3-9c7d-18ef6734fa31.png)

In this case, nothing branched off the red line (in the top several commits), though the dashed pattern changes.

**Comment by sugarmo** [comment]
That's a white point in previous version.

![qq20140516-1](https://cloud.githubusercontent.com/assets/1243254/2992886/ac3ae34e-dc9d-11e3-9b3b-e46d2aa47bff.png)

They just remove the shadow of the points, so...

**Comment by kubat** [comment]
Totally correct.

Please bring back (at least) a dot outline.

**Comment by rowanj** [comment]
That's a bug; they're supposed to be present.

**Comment by rowanj** [comment]
@kubat @sugarmo 
They're working on my two test systems, can you please add:
- GitX version  (0.15.????)
- OS X version

**Comment by kubat** [comment]
Version 0.15.1884 dev (0.15.1884)
OS X Version 10.9.2

**Comment by rowanj** [comment]
Thanks.  Very strange that I haven't seen this.  I've found a suspicious line, and will see if that helps in the next build...

**Comment by rowanj** [comment]
Is this still an issue?

**Comment by kubat** [comment]
Nope! Solved thanks!

-r
