### ISSUE TITLE
Some .gitconfigs stop gitx from working

### ISSUE THREAD

**Issue by pipelineoptika** [rowanj/gitx#33]
As below:

```
[difftool "sourcetree"]
       cmd = opendiff \"$LOCAL\" \"$REMOTE\"
       path =
[mergetool "sourcetree"]
       cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
       trustExitCode = true
```

**Comment by rowanj** [comment]
Diagnosed this with Dave, this was introduced with the increased usage of libgit2 in recent builds.  I think this is likely to be an upstream bug.

**Comment by rowanj** [comment]
If these configuration lines are in place, attempting to open a repository in GitX will result in an error message like:

**The document "repo_name" could not be opened.**
_/path/to/repo_name does not appear to be a git repository._

**Comment by rowanj** [comment]
GitX resumes working when the instances of `\"` are replaced with `"`  -  Does this still work with the difftool / mergetool configuration?

**Comment by pipelineoptika** [comment]
Will check.

**Comment by pipelineoptika** [comment]
Yes, git mergetool works.

It appears that the lines were added by a tool called SourceTree, by Atlassian. What's more, every time SourceTree is opened, it "repairs" these lines by re-adding the backslashes.

**Comment by thisgeek** [comment]
This happened to me too. Upgrading to the latest SourceTree (1.4.0) doesn't appear to help, although I believe you can configure SourceTree to _not_ update your git config.

**Comment by felixbuenemann** [comment]
Same problem, removing escaped quotes helped here aswell, it seems to be already fixed upstream according to the comments on this pr: https://github.com/libgit2/libgit2/pull/599 and this is the fixing commit: https://github.com/libgit2/libgit2/commit/a7d19b975a604b2800ba428a185895241313d1f6

**Comment by rowanj** [comment]
I expect this to be resolved in 0.14.24, released ~1h ago.

**Comment by rowanj** [comment]
Copying this text into my `.gitconfig` now does not break loading repositories.

**Comment by felixbuenemann** [comment]
Thx, works for me.(TM)

**Comment by rowanj** [comment]
Thanks for verifying :-)
