### ISSUE TITLE
Open Recent Doesn't Populate (10.9)

### ISSUE THREAD

**Issue by ecbrodie** [rowanj/gitx#349]
I am using gitx-dev 0.15.1899 on OS X 10.9.3 (both latest versions at publication time). The Open Recent menu for gitx does not work at all. Despite having opened multiple different git projects, no projects are ever populated in the Open Recent list. The only item in it is a greyed-out "Clear Menu" option. Thank you.

**Comment by mczepiel** [comment]
FWIW, works fine for me in 10.9.4 and Version 0.15.1949 dev (0.15.1949)

I had a populated recents menu, cleared it, and then opened several repos and they appeared in the recent lists as expected. Still populated on relaunch. And after clearing, relaunching leaves it empty and accepting new documents.

**Comment by ecbrodie** [comment]
Closing. Le shrug
