### ISSUE TITLE
Need a way to prevent smart-quotes

### ISSUE THREAD

**Issue by ecbrodie** [rowanj/gitx#351]
Whenever I use single or double quotes in a commit message, gitx will automatically convert them into "smart-quotes" (ie, the quotes are angled based on whether they are at the start/end of the quote phrase). This is not desired behaviour. This is likely happening due to gitx's apparent usages of automatic Apple language features (I say this because of the autocorrect behaviour I witness in gitx).

I recommend that we either disable the automatic conversion to smart-quotes in gitx, or that an option is added to the app preferences to enable/disable this behaviour.

**Comment by dbrnz** [comment]
System Preferences/Keyboard/Text can be used to disable smart-quotes -- having "..." change to an ellipses character is a pain!

**Comment by ecbrodie** [comment]
Thanks, @dbrnz . Given this is a Mac OS X feature and not a gitx bug, I'm going to close this issue.

FYI, I still like the smart dash substitution, so I kept the feature in System Preferences on and just changed the single-double quote substitution to use normal straight quotes (ie, without substitution).

**Comment by minrk** [comment]
Is it possible to remember changes to these settings beyond the system-wide defaults? TextEdit has its own preferences for smart quotes, etc., which take priority over the Keyboard prefPane. That behavior makes more sense to me than requiring that I disable smart quotes system in order to change behavior when writing commit messages.

**Comment by njvack** [comment]
In my build of this (0.15.1964), there's a menu setting for the global application (Edit -> Substitutions) that is greyed-out. In addition, this:

`$ defaults write net.phere.GitX SmartQuotes -bool False`

should, I believe, disable smart quotes in most applications, but that setting is not respected. Yes, I can disable smart quotes system-wide, but that's not really what I'd like to do.

In light of this, I'd respectfully suggest that this is indeed a bug, or at least a FR.
