### ISSUE TITLE
Sibling banches disappeared from the tree view

### ISSUE THREAD

**Issue by firedev** [rowanj/gitx#389]
Suddenly I realized I don't see sibling branches anymore. Here is what I am talking about.

Gitx:
![](http://cl.ly/Y4ou/Image%202014-10-17%20at%202.38.54%20pm.png)

SourceTree:
![](http://cl.ly/Y4tf/Image%202014-10-17%20at%202.39.45%20pm.png)

**Comment by ghost** [comment]
You selected to only show “master”, if you click on “All” you'll see all the branches.

**Comment by firedev** [comment]
I see, thanks! Not sure when did I change that, never noticed these before.
