### ISSUE TITLE
Snow Leopard support and __ARCLite__ warning.  Discussion welcome.

### ISSUE THREAD

**Issue by rowanj** [rowanj/gitx#40]
This issue is for the discussion of warnings of the below format as seen in console messages or system logs when launching GitX.

```
objc[63026]: Class __ARCLite__ is implemented in both <...>GitX.app/Contents/Resources/../Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit and /usr/local/bin/gitx.
One of the two will be used. Which one is undefined.
```

The **ARCLite** warnings in the format seen above is due to targeting OS X 10.6 Snow Leopard with Objective-C Automatic Reference Counting (ARC).  There's a support library that is automatically linked in (non-optionally) to support it on pre-Lion systems.  Because we're using Objective-Git as a dynamic library, both the GitX-linked and ObjectiveGit.framework-linked version are found on startup; and the dynamic loader prints this warning.

Fortunately, both versions are identical, so there should be no material effect on the running of GitX due to this.

I'm contemplating two primary approaches to resolving this issue, they are not exclusive.
1. Stop targeting OS X 10.6 Snow Leopard.  Lion has been out since July 2011, and most developers I know have upgraded every Mac they own months ago. I know well the pain of being stuck with bugs that have been fixed for a new platform, but I'm among a very small set of active developers, and I have to draw the line somewhere.
   **This will happen soon after OS X 10.8 is released, unless somebody steps up to maintain (test and support ongoing development on) Snow Leopard**.  Supporting older platforms takes a disproportionate amount of resources, and I'm not going to compromise development for Lion and soon Mountain Lion for the minority that choose to stay with an old platform.  New platforms provide features like more reliable file change watching, native ARC with weak references, and other goodies that help make better programs with less effort.
2. Build and link third-party frameworks as static libraries.  This has some other minor benefits like reducing the download and application size, and eliminating duplicated and dead code; but has the drawback that it's not a supported format for plain 'OS X Framework' targets, so would involve some relatively intrusive modifications to the upstream project layout, which is an ongoing maintenance issue.

**Comment by rowanj** [comment]
Option 3: Stripping the `__ARCLite__` symbols from one of the built products is an option, but I'm disinclined to do so due to its nasty intrusive effects on the build system, especially w.r.t. dependency tracking (getting it to re-build/re-strip appropriately  without forcing a lot of repeated work for each build)

**Comment by earwin** [comment]
GitX 0.14.34 + Lion 10.7.4 - same problem, so it's not SL-specific

**Comment by rowanj** [comment]
It occurs on all platforms because of the SL compatibility.  It's a warning only, and is quite safe to ignore.

**Comment by khoan** [comment]
watching...

**Comment by rowanj** [comment]
GitX's Snow Leopard days are numbered; I'd like to get the existing bugs closed off before moving the target to Lion+ (so that the last SL build is stable enough for long-term use without updates), but I'm now completely without an SL machine to develop or test on.

Mountain Lion is out now, and current versions of Xcode aren't available for anything older than Lion.

Does anybody still use GitX on Snow Lepoard?  I don't collect any deployment or usage data, but it seems unlikely to me; as Apple developers are under pretty consistent pressure to stay on up-to-date platforms.

**Comment by emptyflask** [comment]
I'm a Snow Leopard user, since Lion ruined a number of things, and Mountain Lion isn't supported on my still-awesome Mac Pro 1,1. Hopefully I'm not the only developer that doesn't appreciate the iOS-ification of OSX.

**Comment by rowanj** [comment]
That's a fair point - thanks for speaking up, I was beginning to think that Snow Leopard developers were extinct; not just endangered :-)

I think I've come to terms with most of the interface changes well enough.  I think one of my only remaining peeves is with the consistant removal of colour distinction from icons and buttons.  Rounded-blue and rounded-grey is not nearly enough variety for peripheral recognition.

**Comment by rowanj** [comment]
It seems that either Mountain Lion is suppressing the warning, or building with Xcode 4.4+ is no longer generating it.  Can anybody check current GitX-dev (0.14.46+) against an earlier platform to see if the `__ARCLite__` warning is still shown?

**Comment by urkle** [comment]
Rowanj,  I also use Snow leopard as my primary desktop still. (Mac Pro 1,1 machine as well)  And have a dual-boot Mac Mini for liion/mtn lion testing/development.    the ARCLite command line warning isn't showing up anymore for me on the 0.14.51 build.  And in reality I still have to support Snow Leopard as there is a large set of users that still only have snow leopard (or are only capable of running snow leopard).  So for any Humble Bundle game port I do to OS X, 10.6 is the minimum I have to support.

**Comment by jaywilliams** [comment]
@emptyflask I'm in the exact same boat as you. Mac Pro 1,1, and still running Snow Leopard.

**Comment by rowanj** [comment]
Okay, I'm convinced to keep 10.6 support around for a while yet, then.  Do keep in mind that I don't have it myself anymore, so I'll be leaning on the developers that do to report any platform-specific bugs as best as they can. My target audience is 'you', the developers (not the long-tail of your users) - so this question may come up again before you're done _targeting_ 10.6.

Please be assured that users on to-be-deprecated platforms will be given good warning, and outstanding bugs will be resolved first - the last build should be a good one.

Given that, and the fixing of the warning - I'll close this issue.
