### ISSUE TITLE
Tags no longer appear in graph

### ISSUE THREAD

**Issue by hswolff** [rowanj/gitx#41]
The last time the tags appeared in the history graph was in versino 0.14.16 (I went back and downloaded the previous version from the downloads page to verify).

Since then tags no longer appear in the history graph.

Unclear if this is known or not.

**Comment by rowanj** [comment]
I thought I'd seen something like this; but hadn't tracked it down.  You're right - they're not appearing as reliably as they used to.  I still have some showing up if I select them from the tags section on the right, but not all.

**Comment by rowanj** [comment]
This is almost certainly going to be a relatively simple change to the `PBGitRepository reloadRefs` changes I made at about this build; it was a major instance of pieter's original parsing command line output that I replaced with some libgit2 code - need to investigate how to get all the tag refs properly.

rowanj/gitx@f7bcc7673d978efa3c1266ed1a2519c700bea68f

**Comment by rowanj** [comment]
Of course, now I'm having trouble reproducing it, and tags seem to be loading and displaying just fine.  I'm trying to trace this down to configuration or repository specific issues.

**Comment by rowanj** [comment]
Found a specific repository that reliably reproduces this; the tag `v0.16.0` in libgit2/libgit2 consistently returns the same (wrong) SHA.  I think the one given is a symbolic reference that needs to be properly followed.

**Comment by rowanj** [comment]
@hswolff Can you please check the new build (0.14.26) against the repository you noticed this in?  I'm not entirely confident the bug I fixed is the bug you reported; but I definitely fixed a missing tags bug :-)

**Comment by hswolff** [comment]
Yep, just checked, it's fixed.  Thank you. :)  You da man.

**Comment by rowanj** [comment]
Awesome! Thanks very much for the feedback, and for tracking down the introduction of the issue.
