### ISSUE TITLE
language support, please

### ISSUE THREAD

**Issue by oshx** [rowanj/gitx#434]
Hello, I'm korean user.
Above all, thank you for making a great tool.

I meet the broken korean characters.

I leave a commit log as '정기배포' on terminal.
That means 'periodical release'.

It was clean pushed, but gitX show me that message as 'ì ê¸°ë°°í¬' on screen of DIFF part.
So, I wish to you fix this language problem.

**Comment by ashi009** [comment]
I can't reproduce your problem by checking in a file “中文” in branch "中文" with commit message "中文". And everything looks fine with gitx. 

The most likely cause of the problem could be your terminal encoding setting.

**Comment by oshx** [comment]
I'm assure that problem is not caused by terminal. My log was perfectly shown.
I work with 3 windows users. Someone use TortoiseGit, and other use

**Comment by ashi009** [comment]
Sorry I'm not entirely sure about your case.

According to git-commit manual, all messages are stored in UTF8 by default
and has an encoding header for decoding non UTF8 setting. So you might want
to dig deeper to find what is the exact cause, and reopen this issue.
