### ISSUE TITLE
Subject appears atop commit history lines when column too small for refs

### ISSUE THREAD

**Issue by mczepiel** [rowanj/gitx#48]
If the history column is too small to draw any refs that are present for that commit, the subject for the commit will be drawn all the way to the left of the column, obscuring the commit lines.

This does not affect entries that do not have refs despite the tiny space available.

I have a fix; pull request pending.

**Comment by rowanj** [comment]
Pretty sure you mean for this to be closed by that pull request; thanks again for another top-shape patch :-)
