### ISSUE TITLE
Support smooth scaling properly on OS X Retina screens

### ISSUE THREAD

**Issue by rowanj** [rowanj/gitx#57]

**Comment by rowanj** [comment]
I still don't have a retina screen to test with.

Having merged @magicseth's commit for label dragging, I suspect he's the best person to ask about how GitX fares on high-DPI displays - is there anything in particular GitX is missing on retina?  I'm hoping it's just the sidebar icons and such.

**Comment by ghost** [comment]
You can develop for retina using the Quartz Debug tool

http://make.wordpress.org/ui/2012/08/01/dev-for-hidpi-without-retina-mbp/

**Comment by ghost** [comment]
Just got a retina MBP and I can say GitX looks just fine. The icons need new versions, but they’re not terrible.

**Comment by rowanj** [comment]
I've got an rMBP now, and we've already merged new icons in #182
