### ISSUE TITLE
Padding of Commit Message in commit view is wrong

### ISSUE THREAD

**Issue by pilif** [rowanj/gitx#63]
Ever since I switched from the official Gitx to this fork, this little issue has been bugging the hell out of me:

![screenshot](http://cl.ly/image/1e3Q2N0V1S3B/Screen%20Shot%202012-07-26%20at%2021.34.26.png)

IMHO there should be a few pixels of padding between the left border in the commit view and the actual commit message.

Also it would be great if it was possible to set the Font or at least increase the size.

Yeah. It's nitpicking, but GitX is such a beautiful application that small issues like this are really bugging me :-)

**Comment by rowanj** [comment]
Build 0.14.39 is in progress, should be available through in-app updates in the next few hours.

**Comment by rowanj** [comment]
Build 0.14.39 available in the downloads; will become available through in-app updates when AWS CloudFront stops caching the old appcast >_>

**Comment by pilif** [comment]
Holy Sh*t. That was quick! Thanks a lot!

**Comment by rowanj** [comment]
Well, I understand it now a lot better than I did when I broke it :-)
