### ISSUE TITLE
Compile fails in Xcode 4.4 / OS X 10.8

### ISSUE THREAD

**Issue by felixbuenemann** [rowanj/gitx#67]
Build fails to find ObjectiveGit.h (using `rake build_app`):

<pre>
=== BUILD NATIVE TARGET cli tool OF PROJECT GitX WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies

ProcessPCH /var/folders/fj/x09hpwn52851mmpfgldmygv00000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-gzsdpzdhsxnlknffdtmmlxbzmeuv/GitX_Prefix.pch.pth GitX_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/felix/develop/gitx-rowanj
    setenv LANG en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c-header -arch x86_64 -fmessage-length=0 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-sign-compare -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -fasm-blocks -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.6 -g -fvisibility=hidden -Wno-sign-conversion "-DIBOutlet=__attribute__((iboutlet))" "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))" "-DIBAction=void)__attribute__((ibaction)" -iquote "/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/gitx-generated-files.hmap" "-I/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/gitx-own-target-headers.hmap" "-I/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/gitx-all-target-headers.hmap" -iquote "/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/gitx-project-headers.hmap" -I/Users/felix/develop/gitx-rowanj/build/Release/include -I/Users/felix/develop/gitx-rowanj/objective-git/libgit2/include "-I/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/DerivedSources/x86_64" "-I/Users/felix/develop/gitx-rowanj/build/GitX.build/Release/cli tool.build/DerivedSources" -F/Users/felix/develop/gitx-rowanj/build/Release --serialize-diagnostics /var/folders/fj/x09hpwn52851mmpfgldmygv00000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-gzsdpzdhsxnlknffdtmmlxbzmeuv/GitX_Prefix.pch.dia -c /Users/felix/develop/gitx-rowanj/GitX_Prefix.pch -o /var/folders/fj/x09hpwn52851mmpfgldmygv00000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-gzsdpzdhsxnlknffdtmmlxbzmeuv/GitX_Prefix.pch.pth -MMD -MT dependencies -MF /var/folders/fj/x09hpwn52851mmpfgldmygv00000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-gzsdpzdhsxnlknffdtmmlxbzmeuv/GitX_Prefix.pch.d
/Users/felix/develop/gitx-rowanj/GitX_Prefix.pch:6:11: fatal error: 'ObjectiveGit/ObjectiveGit.h' file not found
                #import <ObjectiveGit/ObjectiveGit.h>
                        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
    ProcessPCH /var/folders/fj/x09hpwn52851mmpfgldmygv00000gn/C/com.apple.Xcode.501/SharedPrecompiledHeaders/GitX_Prefix-gzsdpzdhsxnlknffdtmmlxbzmeuv/GitX_Prefix.pch.pth GitX_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
</pre>

<pre>
find . -name ObjectiveGit.h
./objective-git/build/Release/ObjectiveGit.framework/Versions/A/Headers/ObjectiveGit.h
./objective-git/Classes/ObjectiveGit.h
</pre>

**Comment by rowanj** [comment]
Have you got the submodules?

```
cd gitx-rowanj
git submodule init
git submodule update
```

**Comment by felixbuenemann** [comment]
Yes, the submodules are there and at the correct revisions.

**Comment by rowanj** [comment]
Sorry, I'd missed that last section in the initial report when I saw this via E-mail.  It's definitely building for me on Xcode 4.4 / 10.8,  although I've always had a configured build products directory in my Xcode prefs that stopped it from creating build/ folders underneath the source directories; perhaps the project doesn't have the right search paths to find the built framework in the default location.

**Comment by felixbuenemann** [comment]
Just checked, Prefs -> Locations -> Derived Data -> Advanced -> Build Locations is set to "Unique" if that's the setting you are referring to. However changing this setting does not keep seem to keep the commandline build from creating build directories inside the submodules.

Are you building from the command line using `rake build_app` or from the Xcode GUI?

**Comment by rowanj** [comment]
Wow, I'd totally overlooked the `Rakefile` in the project directory - I'd never even noticed it, and certainly haven't updated it along with the changes to the project layout.

The Xcode project is set up with the appropriate target dependencies that pretty much everything 'just works' - I'm pretty sure that it was the only reasonable way to build the project from whatever fork I started from, because libgit2 was built by a shell script build stage within the project.

On my (Mountain Lion + Xcode 4.4) dev machine I use the Xcode GUI, the Jenkins build server (Lion + Xcode 4.3.4) responsible for the deployment packages uses:

```
/usr/bin/xcodebuild -scheme GitX -workspace GitX.xcodeproj/project.xcworkspace -configuration Release build 
```

Sorry for so obviously skimming the details in your original report.

**Comment by rowanj** [comment]
Looking at the Rakefile, I think the issue will be that the `xcodebuild` command-line tool needs to specify a scheme and workspace in order to properly track inter-project dependencies; as this GitX fork is currently set up with.

I don't have any Rakefile expertise of my own to call on for this - so unless you prefer it for some reason that isn't apparent to me I'm considering just removing the file.

**Comment by felixbuenemann** [comment]
Thanks, using xcodebuild does work. Maybe removing the Rakefile and adding a simple build.sh or similar with the command above would be nice.

**Comment by rowanj** [comment]
Good idea :-)
