### ISSUE TITLE
Disable automatic spell correction

### ISSUE THREAD

**Issue by urkle** [rowanj/gitx#69]
The commit message text entry has automatic spell correction turned on.  This gets quite aggravating when it spell corrects programming terms to what it things are "correct" even though they are not.. (nav to nave, taggable to tangables, refactor to refractor).

The only way I can turn it off is through the context  menu, but that only lasts so long as I don't close the window. Otherwise it resets.  Can we please have this turned OFF? or provide a Gitx global menu option to turn it off?

And no, I can't turn it off at the OS system level as there is no ability to do so in Snow leopard.

**Comment by lourenzo** [comment]
Looks like the autocowreck is still there, I'm using 0.14.51.
I unfortunately couldn't build on 10.6, but would be awesome to have an option to disable it.

**Comment by stepheneb** [comment]
I'm using version 0.14.95 dev (0.14.95) and I can't write a commit message mentioning the file named ".tm_properties" ... because it turns into ".™_properties" ... ;-)

**Comment by tiennou** [comment]
I'm not sure it's the spell check mechanism. I suspect the Text Substitution system managed from (sorry, that's translated) System Preferences > Language and Text > Text tab.

**Comment by urkle** [comment]
Actually each text control has it's own private settings for spell checking and text substitutions.. which can be overridden globally on 10.7+.

Simply turning that OFF in the xib would do wonders to make people sane with using this tool.  For some applications the substitution makes sense, but for a Git commit tool for programmers, it doesn't make sense at all to leave that on.

I'm constantly having to retype things over and over as it auto spell checks and substitutes things for me all the time.  Quite annoying when I try to type "fixup blah"  (which it corrects to mix up)

**Comment by stepheneb** [comment]
I disabled **Correct spelling automatically** in System Preferences > Language and Text > Text, quit and restarted gitx ... automatic spell-checking is still enabled

**Comment by GeoffTidey** [comment]
Auto-correction on commit messages is still an issue for me on "GitX 0.15.1964 dev" which apparently "is currently the newest version available."  Running OSX 10.9.5
