### ISSUE TITLE
Downloads / GitX-dev-40.zip contains source not a build

### ISSUE THREAD

**Issue by sbwoodside** [rowanj/gitx#71]
Downloads / GitX-dev-40.zip contains source not a build.

-39 contains a build.

**Comment by rowanj** [comment]
The `GitX-dev-40.zip` link in the list on the [downloads page](https://github.com/rowanj/gitx/downloads) works for me (should be ~4.5 MB, and extract to a ~11 MB `GitX.app` (0.14.40).

Unfortunately, I don't think there's anything I can change directly to hide the GitHub `Download as zip` and `Download as .tar.gz` buttons at the top of the page; which always get an archive of the git tree - is it possible that you got the result of that instead?

If the  dosen't work for you, could you try a direct link to the [builder output](http://builds.phere.net/GitX/dev/GitX-dev-40.zip)?

The in-app update mechanism (`GitX` menu -> `Check for Updates...`) should also work; and is managed without direct human intervention, so it may be a little more reliable.

**Comment by pipelineoptika** [comment]
I'm seeing the same behaviour as @rowanj; the link produces a zip file containing only the app bundle.

**Comment by rowanj** [comment]
Thanks @pipelineoptika.

I've sent a support ticket to GitHub about the layout of the project downloads page - I assume this was due to interface confusion over the 'Download as zip' button which is a part of the immutable layout of that page.

(unless @sbwoodside suggests otherwise)

**Comment by sbwoodside** [comment]
Ahh, that's exactly the problem, and I agree that github's layout is very confusing.

(And I will remember "The Design of Everyday Things" for why I should say this is github's fault and not mine :-)

thanks

**Comment by rowanj** [comment]
No problem; I ran into the issue myself a while back when I was trying to figure out the project downloads stuff, hopefully GitHub will improve that UI soon.
