### ISSUE TITLE
Installing command line tool broken on Mountain Lion

### ISSUE THREAD

**Issue by rowanj** [rowanj/gitx#75]

**Comment by juradoz** [comment]
Worked fine from me. 0.14.51 under ML 10.8.2.

**Comment by rowanj** [comment]
Looks like it may only be a testing issue - it doesn't seem to work from Xcode builds that are in the build products directory, but works okay for downloaded/installed packages.

@juradoz thanks for testing this :-)

**Comment by juradoz** [comment]
according to main.m, it isn't even implemented…

But I'm still investigating...

**Comment by rowanj** [comment]
Seems to have been transient, or specific to my dev environment at the time.
