### ISSUE TITLE
xcrun doesn't work for me

### ISSUE THREAD

**Issue by akirk** [rowanj/gitx#80]
Since gitx .46, it won't start at all anymore. This seems to be due to xcrun which uses 100% cpu while producing no result.

I don't know if I have my system misconfigured but I also can't find any info on the Internet on how to get xcrun working. I only have the Xcode command line tools installed and my version of git has been installed through homebrew.

Any tips? Would it be worth for gitx to check if xcrun is doing something useful? Wouldn't it be good for gitx to cache the last-known position of git in the filesystem and use that without always invoking xcrun? (btw, `which git` does work for me)

**Comment by akirk** [comment]
As a follow-up, `brew doctor` told me this:

```
Warning: Your xcode-select path is set to /
You must unset it or builds will hang:
  sudo rm /usr/share/xcode-select/xcode_dir_*
```

So I executed that command and now:

```
$ xcrun git
xcode-select: Error: No Xcode is selected. Use xcode-select -switch <path-to-xcode>, or see the xcode-select manpage (man xcode-select) for further information.
```

but I don't have a path of xcode to point to. 

[Comment by mxcl](https://github.com/mxcl/homebrew/issues/10245#issuecomment-4499243) on the issue

```
I believe brew doctor tells you not to set xcode-select to /. It exposes a bug in xcode-select that causes it to hang forever.
```

But after all, this makes gitx work again. So maybe you can keep this for further reference.

**Comment by rowanj** [comment]
@akirk thanks for reporting this - Seems to me that the flaw is that I assumed people using GitX would have Xcode installed;  GitX still needs to find the `git` command line tool for several operations, and I switch to using `xcrun` to find it recently (yes, with .46, I believe).

To anyone else that hits this issue, another workaround is to set an explicit path to the Git executable in the GitX Preferences pane; assuming that you have git installed, but not Xcode.  That should bypass the search that is hanging.  Another option is to grab Xcode from the App Store - but that's a big download for somebody that isn't using it.

I think I'll re-open this for the change to check `xcrun`'s configuration before trying it; that's a legitimate GitX bug, in my opinion.

**Comment by akirk** [comment]
Just as a side note: you actually can't set the explicit path to the `git` executable in GitX because it wouldn't start. It hangs even before it opens a window. Therefore (with the current version) it is really necessary that you don't have a blocking `xcrun` to startup GitX.

**Comment by rowanj** [comment]
I haven't found a good way to cancel xcrun if it hangs, and I'm reluctant to add more sophistication to Pieter's task/pipe infrastructure that I'm trying to phase out entirely in favor of libgit2.  For the moment I've moved the 'xcrun' alternative to be the last attempted, so while the failure mode isn't good, it should be at least improving the case where the user has Xcode but no command-line git installed.

**Comment by akirk** [comment]
That actually sounds like a pretty good solution to me. Thank you!
