### ISSUE TITLE
Commit list loses selection when app becomes inactive

### ISSUE THREAD

**Issue by bgulanowski** [rowanj/gitx#9]
Selecting a commit and switching to another application causes the selected commit to revert to the most recent commit in the commit list. This requires searching for the commit again, etc.

The app should preserve the user's selection across refreshes. This might be as simple as setting the preserve selection flag on the associated array controller.

**Comment by rowanj** [comment]
I can't reproduce this on Lion.

(edit: the bug exists, but is not tied to focus/active state of the window, [see comment #2](https://github.com/rowanj/gitx/issues/9#issuecomment-3171509))

**Comment by rowanj** [comment]
I had this happen spontaneously while working on the ARC conversion - I think this may actually be a symptom of the commit list reloading, not just losing focus. I've noticed that the reload is happing a lot more than need be, I think some NSDocument/Auto Save notification is slipping in there and causing it to be reload way too much.

The reload code should however preserve the selection; absolutely.

If you're still interested in/able to repeat this bug @bgulanowski : can you tell me if you're on Snow Leopard/Lion, and if it happens without Xcode having the same repo open?

**Comment by rowanj** [comment]
Given that I'm pretty sure it's the commit list reloading that is clearing the selection, that's what I'll be focusing on to fix this.

**Comment by ches** [comment]
This is the most frustrating thing about daily use of GitX-dev for me at this point -- I don't know if something particular about my setup exacerbates it, but the commit list reloads _way_ too frequently, making the lost selection a real pain when I switch between GitX and my editor while referencing something from an earlier commit, for instance, and switching back to GitX my place is lost.

I'm on Snow Leopard, not using Xcode, latest GitX-dev from Sparkle. A couple of cases where I frequently find that it occurs:
1. I save some existing file in my project (any file).
2. Running my project test suite -- the commit list reloads each time another test file is executed, so you can forget trying to browse something in GitX while the full test suite is running.

Happy to provide any further info requested!

**Comment by rowanj** [comment]
The current repository watching code is far too zealous about which events mean changes that need to be reloaded; I think it needs to filter the file system events down to:
- changes to the repository (i.e. `.git/*`)
- files that are in the repository (changes to tracked files)
- untracked files that are _not_ ignored

On the upside, you can turn off `Automatically refresh repository on change` in the preferences for a good chance of avoiding this; but obviously that's not a great solution.

edit:  Also yes, I agree that this is probably the most frustrating single issue in the project at the moment, and would dearly love to fix it.

**Comment by ches** [comment]
Thanks for the update!

I'm curious though about your last two bullet points -- if it's only the commit list that is reloaded by the watching, why should any file changes other than to the `.git` dir cause refreshes? Or does the same watch also apply to the Stage view?

I wish I were a little more proficient with Cocoa. Where does the fsevent handling code live?

**Comment by rowanj** [comment]
From what I recall of my last foray into the code, there's one OS notification listener for file system changes, which processes the details of event messages into repository and working copy changes; repository changes refresh the sidebar, history view, and commit view; while working copy changes refresh only the commit view.

This is my rationalization of some code inherited from mainstream and/or GitX (L) and may be wrong entirely.  It seemed to have gone through two or more generations.  The code itself lives mostly in [PBGitRepositoryWatcher.m](https://github.com/rowanj/gitx/blob/master/Classes/git/PBGitRepositoryWatcher.m)

**Comment by rowanj** [comment]
I've added some logging and found that the majority of refreshes I was seeing were due to changes to the various `.lock` files within the `.git` dir; which don't of themselves indicate any change that requires a refresh, so I'll start by specifically ignoring files matching that pattern when the filesystem watcher events come back.

**Comment by rowanj** [comment]
This seems to now be happening _significantly_ less; but I'm not yet happy with it.  I think the combination of the zealos repo watcher and libgit2 work was resulting in refreshes triggering refreshes... not good.

Remaining work on this issue:
- cut back the repo watcher's event firing more
- maintain selection and scroll position when the commit list refreshes

**Comment by rowanj** [comment]
I think this has improved to the point the issue can be closed.

Prototype fix in 0.14.38+ cut this way back to the point that our largest repo can be effectively browsed while both Xcode and Eclipse have their projects open and running (a previously pathologically bad case).

There are some performance regressions due to the way this code works (it's effectively running `git status` and comparing the results) - but I think it's still acceptable, and can be better improved by other work like re-writing the rev-list parser.
