### ISSUE TITLE
Repositories are opened twice when restarting

### ISSUE THREAD

**Issue by sjmadsen** [rowanj/gitx#91]
If I quit GitX with open repository windows, when I restart it, those repositories are each opened a second time and I end up with a extra copy of each. Quitting again and restarting doubles that again, so there are now four copies of each repository.

It seems like GitX is replicating the Lion/Mountain Lion behavior of automatically re-opening documents at launch.

**Comment by rowanj** [comment]
The enhancements to Lion & Mountain Lion's management of NSDocument-based applications are certainly not interacting well with GitX's pre-existing restoration of old windows.

Fixes are unfortunately made more difficult by supporting OS X back to Snow Leopard.  It could be that I just need to detect the OS version during the launch and bypass the manual code for OS 10.7 up, but that'd also have to be indicated in the preferences panes for this behaviour, too.

**Comment by sjmadsen** [comment]
I think delegating this behavior to the system is the right choice on 10.7+. Removing the preference from the GitX pref pane for those users is ideal, but I don't know how difficult that is, layout-wise. It's probably a huge pain if it's in a nib (I haven't looked). Maybe just grey it out on 10.7+?

Do you keep any metrics on the OS version breakdown? If only a small minority of users are on 10.6, it's unfortunate to let a problem like this persist for the majority.

**Comment by rowanj** [comment]
I think delegating is a good choice; I know there are at least a handful of 10.6 users active on the GitHub project, but I don't have the stats for the distributed user base at large.  Sparkle.framework has the option to send some basic system stats (OS, # CPU, RAM, etc.) as query parameters when it gets the XML defining the latest version, so I've been looking at collecting those today.

I'm leaning toward removing the preference entirely; I'm not a fan of version-specific code, so each platform would get whatever the OS provides, which I think for 10.6 would be "don't open anything by default."

**Comment by tfeb** [comment]
I'm on 10.7 so may be biassed, but I'm pretty sure that if I was on 10.6 I'd be happy for it not to reopen repos by default, so long as they appeared in the recents list.  However I definitely want `gitx` from a shell on its own to open the repo corresponding to the current directory (because, in practice, I always start the app like that).  Currently the behaviour there is confusing and you often get two windows on top of each other (so you don't even notice there are two windows on the same repo open).

**Comment by rowanj** [comment]
0.14.57 delegates the open sequence entirely to the OS; which I'm very happy with on Mountain Lion.

I expect that the Open Recents dialogue is going to fill the gap on earlier platforms (I assume that's what it's there for)

**Comment by tfeb** [comment]
Works for me on Lion, thanks!

**Comment by eirc** [comment]
Thanks!!

**Comment by rowanj** [comment]
A couple of days in, I'm still very happy with this change myself; so I'll close this issue.

@sjmadsen FYI; Issue #103 will gather stats about the OS breakdown

**Comment by sjmadsen** [comment]
Since we started this conversation, I'd turned off the preference myself. I think it's be good for 10.7+ users not to be confused when that option was present.

Thanks!

**Comment by rowanj** [comment]
The preferences are now gone, too.  It's operating-system and user-initiated behaviour only.  No auto-pop-stuff-up.
