### ISSUE TITLE
Doesn't work with Git 1.8

### ISSUE THREAD

**Issue by firedev** [rowanj/gitx#97]
Just says something like `file://localhost/Users/user/Sites/repo/ does not appear to be a git repository.`  for every git 1.8 repository.

**Comment by rowanj** [comment]
Definitely looking into this, I've changed the repository discovery significantly in 0.14.57 to alleviate some other issues.  The new way is much more dependant on libgit2's `git_repository_discover` function, which I expect to be more resilient than the previous mechanism; and more up-to-date with current `git` version.

**Comment by firedev** [comment]
Looks like 0.14.57 is working with git 1.8. Is there anything else that need to be fixed so this ticket can be closed?

**Comment by rowanj** [comment]
I guess it was just fixed by updating libgit2 - I missed this comment because I'd not actually made any specific changes toward it.  If it's working for you, I'm happy to close.
