### ISSUE TITLE
When open gitx from command line in a reposotory, it's open twice

### ISSUE THREAD

**Issue by nledez** [rowanj/gitx#99]
Hi,

Case:
- GitX is close (yes I close it some times)
- Open a terminal (iTerm 2 in my case, with zsh)
- Go in a repository
- Type "gitx"

It's open GitX, and my repository too. But in two window :(

If GitX already fired, only one window is open.

Thanks

**Comment by grappo** [comment]
same issue using bash in both terminal.app and iterm2.app.
using "gitx ." seems to work better though. EDIT: actually not! i just didnt notice the second window!  (duh..) ;)

**Comment by rowanj** [comment]
This should be resolved in GitX-dev-57 (now in the Downloads page, allow 24 hours for in-app updates to show it).  You may need to re-run the "install command line tools" from the GitX menu.

**Comment by nledez** [comment]
Work perfectly, without command line tools update.

Many thanks !!!!

**Comment by rowanj** [comment]
Thanks for reporting and testing it :smile:
